require: rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  AllowedMethods:
    - 'describe'
    - 'context'
    - 'it'

Naming/FileName:
  Exclude:
    - 'lib/Ryze.rb'
    - 'spec/Ryze_spec.rb'

RSpec/NestedGroups:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 7
  AllowSubject: true
