module Ryze
  class MatchResource
    BASE_URL: String

    def retrieve_match: (match_id: String) -> Match

    def retrieve_match_list_by_puuid: (puuid: String, **Hash[Symbol, String | Integer] params) -> Array[String]
  end
end
